### ISSUE TITLE
Style labels under issues on project page

### ISSUE THREAD

**Issue by beck410** [code-for-nashville/brigade-pulse#34]
- add padding to labels
- labels should be display: inline with margin on left + right

**Comment by AndyMeagher** [comment]
Where should the labels be displaying? not in the bottom left corner like they are?

**Comment by beck410** [comment]
i don't see why not - seems like a good place for them

**Comment by AndyMeagher** [comment]
ok, just checking on what you meant by this issue...is it just the left padding then?

**Comment by beck410** [comment]
mainly the display property - some issues i've seen have over 5 labels and it looks messy having them stack on top of each other

**Comment by beck410** [comment]
and just a tiny bit of padding on the label so the text isn't touching the corners

**Comment by AndyMeagher** [comment]
gotchya!

**Comment by AndyMeagher** [comment]
styled them inline and changed the font from white to black because I saw that there is one hex color that is white...
