### ISSUE TITLE
Add feature to filter and rank brigades on brigades page

### ISSUE THREAD

**Issue by beck410** [code-for-nashville/brigade-pulse#38]
Possible filters
- those with current projects
- those with open issues

Possible rankings
- most contributions
- most contributors
- most active (all instead of top 5)
- most issues 
- most projects
- most events

**Comment by beck410** [comment]
Let me know any data you need for the rankings/filters and i'll work on putting them on fb

**Comment by AndyMeagher** [comment]
- Hey Beck, I pushed up a filter to view Brigades by name and by total projects...There's an option in for filter by Ranking that's not doing anything yet
- The problem with that is that the ranking lives in the static JSON file we are eventually getting rid of. For the home page we are ng-repeating through that...If you go to the main controller and console log vm.brigades on the home page, you will see the ranking...It's an array of arrays with the Brigade name, city, and ranking...I don't know if there would be a way for you to grab that ranking number and push it to firebase. You'd have to find and match the brigades first, and I know the JSON file doesn't actually have all of CFA's listed brigades for some reason.
-Anyway, I feel like maybe once we get more info as to how the backend is going to be functioning, the front-end could actually benefit from some refactoring. 
-Any comments, ideas, suggestions? I'll continue to play around with things
