### ISSUE TITLE
Build out Backend

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/brigade-pulse#4]
I'm planning on using RethinkDB and a python daemon to periodically aggregate all the data from the CFAPI and push it to a table.  From there I will setup an API so that we can make an AJAX request from the front end and pull in the data.

This way we will at least begin getting up-to-date data and pulling it into a persistence layer.

@GGross5213 If you want to help with this I can provide assistance with RethinkDB

**Comment by GGross5213** [comment]
I am very down to help with this.
