### ISSUE TITLE
Add Vote/Polling Feature

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/brigade-pulse#5]
@beck410 @colbydehart @AndyMeagher @bdfinlayson 

I was thinking about potential uses for BrigadePulse at the National Day of Civic Hacking.

I thought it would be cool if users could upVote projects they were interested in seeing in their city while exploring through different brigades.

We could crowd source features the community would like to see and have data to help prioritize new datasets coming out of the open data portal.

**Comment by bdfinlayson** [comment]
That sounds like a great idea. What kind of back end will be available for this?

**Comment by neolytics** [comment]
I'm planning on rethinkDB as it is very powerful and I know it quite well.

Jon Staples, M.S.2
Data Scientist
NextGxDx

Phone: 803-272-8073
Twitter: @civic_hax

**Comment by sheikahamed** [comment]
Sounds good. Please let me know, if I can be of any help with this effort.
I will be available.

**Comment by beck410** [comment]
I'll help on the angular side of things
