### ISSUE TITLE
Deploy BrigadePulse to a server

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/brigade-pulse#6]
@jcockhren @beck410 

CFA proper is interested in this app and we want to have this deployed by the National Day of Civic Hacking.

I registered www.brigadepulse.us today so we've got a domain.  We could stand this app up today in its current form and then add to it over time.  It would be really big to have this so we can market it and demonstrate that we can build things as a team.

Where should this go? AWS? I think Metro's servers are a perfect place for this.  What is the burden on installing services on Metro's servers?

**Comment by bdfinlayson** [comment]
Awesome!

**Comment by jcockhren** [comment]
This looks like an purely front-end app. We could put it on the Metro Servers, no problem. But this can also be hosted on S3.

**Comment by neolytics** [comment]
It is currently a front end app, but will not stay that way.  There is a
fairly big need for a backend, but we couldn't deploy that at HackTN.

On Tue, May 5, 2015 at 11:39 AM, Jurnell Cockhren <notifications@github.com>
wrote:

> This looks like an purely front-end app. We could put it on the Metro
> Servers, no problem. But this can also be hosted on S3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-for-nashville/project-x/issues/6#issuecomment-99134828>
> .
>



-- 
Jon Staples M.S.2

[Data Scientist | NextGxDx | www.nextgxdx.com]

**Comment by jcockhren** [comment]
> It is currently a front end app, but will not stay that way.

ok. Then let's host on the metro servers in anticipation.

**Comment by zachmccormick** [comment]
Hi all,

As posted in the Slack room, I just pushed this to a free-tier Heroku instance.  I'll be in SF until Saturday, but maybe I can go to a coffeeshop and meet up with people a week from today (Sunday) and work on pointing the domain to the new app + getting the front-end displaying properly.

Right now we get a "free tier" dyno for free, as well as a basic MySQL database of very limited size for free.  I have no problem upgrading these to paid and having my consulting company sponsor the app when the time comes to move out of the free tier!

**Comment by beck410** [comment]
@zachmccormick great! Let's aim at meeting up when you're back (Sunday sounds good) - I'll post a time and place in the slack channel this week and see if people can make it
