### ISSUE TITLE
feature: Add run_all_scrapers management command

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/brigade-pulse#68]
Add a django management command that will allow local users to get the most recent  data from the various data sources (meetup, github, cfapi) downloaded into the local database.

**Comment by neolytics** [comment]
@zachmccormick 

I wrote a command for this as it was pretty trivial, but I noted that a command for running at least one of the scrapers was recently added.  Is this still an issue?

I haven't been able to test it's functionality because of difficulties with getting postgres and Django coordinated

**Comment by neolytics** [comment]
@zachmccormick So from what we discussed this isn't really even necessary?  If so I'm not going to worry about it and close the issue

**Comment by zachmccormick** [comment]
Oh oops I forgot to close this.  I already added it :D

--
Zach McCormick
317-443-2799
