### ISSUE TITLE
Continue Developing out Activity Metrics

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/brigade-pulse#7]
Andrew Hyder at Code for America has gathered the interest of a PhD candidate from Berkeley to develop "Activity" metrics for the CFAPI.

@sfall Christian! We can do better than them!

**Comment by sfall** [comment]
Yes we can! What sort of metrics do you think we should look at?

**Comment by ondrae** [comment]
I found this randomly on the [Civic Issue Finder](http://civicissues.herokuapp.com/geeks/civicissues)

Some questions I have are:

#### Projects
* How to define an active project? Commits in the last week? What about stable code that doesn't need commits?
* How to determine a dead project. No commits? No users? Broken build?
* We've [added support](https://github.com/codeforamerica/cfapi#civicjson) for `status` and `tags`. Which status and tags should we start encouraging people to use? Alpha, Beta, Launched? Health, iOS, Featured? I did a quick perusal of what was [out there already](https://github.com/codeforamerica/cfapi/issues/204#issuecomment-89083734).

#### Brigades
* How many different people are committing to their projects?
* How many people are commenting on their GitHub Issues?
* How often do they make a new project?
* Whats the rate of new people that start committing to their code?

**Comment by neolytics** [comment]
My current theory is that most active projects will tend to follow zipfian (power law) distributions.  There will be at most a handful of major contributors and then a longish tail of people that contribute relatively little.

The metric guy had a 99% confidence interval on that observation, but that was on a very small set of data.

@ondrae Actually, we could use your help on this.  Do you have a list of projects that you consider "Successful", a list of failed projects, and a set of something in between?  We are trying to get training data to see if there are observable trends between these different classes of project.

**Comment by neolytics** [comment]
@ondrae 

Active Projects
The stable code one is an issue that is hard to detect.  You'd probably need a "status": "stable" flag, and have to rely on users.  Otherwise it's difficult to determine the difference between a functionally complete project and one that has been abandoned.  I'll marinate more on this and see if I can come up with some ideas.

Dead Projects:
Could cross reference primary users activity against timestamps of recent projects?  Most of the dead projects I've seen have been associated with a project lead getting a new job or a kid or something and basically taking off.

Flags: 
I'd add "Stable" or "Functionally Complete" to that list.  Could help with the dead/complete issue.

Brigades:

We can build some of this into BrigadePulse.  I'll setup some issues and see what we can do.

**Comment by beck410** [comment]
@sfall @GGross5213 - are any of you interested in continuing building this activity metrics out for ranking brigades? We are going to build a very simple algorithm on the frontend for now to bring down real data -

**Comment by sfall** [comment]
Yes! Is there a database to store data yet, or do you just need API calls?

**Comment by beck410** [comment]
i'm using firebase for a caching layer but would be good to build out a backend - would you be willing to keep working on it?

**Comment by sfall** [comment]
Sure. I read on issue #4 that Jon intended to use RethinkDB. I'll start organizing collections and documents for it.

**Comment by beck410** [comment]
great! I'm pretty sure @mshenfield is familiar with rethinkDB and would be a good person to talk to about it

**Comment by mshenfield** [comment]
Hey @sfall I'm still relatively new to RethinkDB but I'd be up to learn together. I was planning on putting some work into it anyways on Tuesday or Thursday.

**Comment by sfall** [comment]
@mshenfield That's cool. I'm gonna start poking around it tomorrow.

**Comment by mshenfield** [comment]
@sfall Anyone interested I'll be pushing up changes on [my fork today](https://github.com/mshenfield/brigade-pulse)

**Comment by AndyMeagher** [comment]
How's rethinkDB going @mshenfield ?

**Comment by beck410** [comment]
@AndyMeagher  when are you back in Nashville? I've stopped work on the frontend until we get a backend working
