### ISSUE TITLE
wiki:  Add postgresSQL install instructions RHEL

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/brigade-pulse#73]
On Centos7 the process was

`sudo yum -y install postgresql postgresql-contrib postgresql-devel`

If you attempt `pip install -r requirements.txt` without postgresql-devel you get a gcc failure.

**Comment by mshenfield** [comment]
On OSX you got

`brew install postgres`

Set the environment variable `PGDATA` to the path where you want postgresql to live by adding this to your terminal `.*rc` file.

`export PGDATA=[INSERT PATH TO POSTGRES HOME HERE]`

Then you can run `pg_ctl init` and `pg_start` to have Postgres running in the background and logging to standard out.

To create the database run `createdb brigadepulse`.

**Comment by mshenfield** [comment]
Zach grabbed this one!

**Comment by neolytics** [comment]
I'm re-opening this one as it was defined on OSX, but the process is different on different operating systems.  I'll update this as postgres install for linux, debian/RHEL
