### ISSUE TITLE
refactor:  Set environmental variables as default input for API credentials

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/brigade-pulse#75]
In general I like to avoid having people do awkward stuff like create local files for managing credentials.  I'd advocate sourcing them in as environmental variables and avoid that confusion all together.

**Comment by neolytics** [comment]
Ah, I see.  So there is a basic setting configuration and a production setting config.  I'd probably just have them both go from env vars and avoid the need to have a secondary configuration mechanism.

**Comment by neolytics** [comment]
I see the rational of why this is being done.  Going to kill this one.

**Comment by zachmccormick** [comment]
Yeah - the alternative is a `.env` file, which works only for `foreman start`, as Heroku will load those into your environment before running the web dyno and worker dyno on your machine.

Doing it the Pythonic way allows us a little more flexibility.  For instance, in one terminal you can run a celery worker and in another a `./manage.py shell` to manually trigger celery jobs for testing.  I'm not sure how to do that as easily with `foreman start` and a `.env` file, but this sort of testing for celery jobs is fairly common, so I wanted to make sure to support that use case.

**Comment by zachmccormick** [comment]
in prod, it actually does pull from environment variables, so I can keep API keys out of the repo entirely (we're using my github and meetup API keys right now ;-) )
