### ISSUE TITLE
task: Forward heroku domain to www.brigadepulse.org

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/brigade-pulse#84]
@zachmccormick I registered the url above a while ago through AWS.  I haven't touched the heroku side of things, but the URL is available.  Let me know what you need from me to do the forwarding.

**Comment by zachmccormick** [comment]
Can you add a CNAME record to point to `
nashville-brigade-pulse.herokuapp.com`?  It should *just work* according to
heroku.

-Zach

--
Zach McCormick
317-443-2799
